language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_deps

before_script:
  - Rscript -e 'library(devtools); document(clean=TRUE, reload=TRUE);'

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - git config --global user.email "luckyrandom@gmail.com"
  - git config --global user.name "Chenliang Xu"
  - ./deploy.sh -s master-src -d master -c 'make -k prebuild'

env:
  global:
    secure: "WteE7/dyLk2gQduG29OsSfwSEn3nD3GSPOn16aOhXLgVwJKnjBcD3EtrJ2Z1RoQXw7ERSrkdxz+vpIBhSofcL0FaREMCzsPflB8lAGl1t4cApEj+Lx/N5TMw+7Whwmxdd5IK++FW33dxkBE22vkcTnlLusvK2OJ6IegxMure9V4="
    
branches:
  except:
    ## exclude the deploy branch from build on travis-ci
    - master
    
