language: c

sudo: required

before_install:
  - sudo add-apt-repository --yes ppa:george-edison55/cmake-3.x
  - sudo apt-get -qq update
  - sudo apt-get -y cmake
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_deps

before_script:
  - Rscript -e 'library(devtools); document(clean=TRUE, reload=TRUE);'

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - git config --global user.email "luckyrandom@gmail.com"
  - git config --global user.name "Chenliang Xu"
  - ./deploy.sh -s master-src -d master -c 'make -k prebuild'

env:
  global:
    secure: "mrBdQPDAnoKUpRc21YSbP6LVsJpz1u6/5oS1Ypnypg5bFzjX33akCAonMcq6qtNXogHDolWC5ADcUDYE+PAV3Nt1ivb61IQhQCm+emE0FjYcQ5W2kiE4sVwPIWR+N+3R4LJ/6zC7j4O+SZUwQbWVlKOx1I0zKyuy1PHOBOxZDyc="
    
branches:
  except:
    ## exclude the deploy branch from build on travis-ci
    - master
    
