language: c

sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_deps

before_script:
  - Rscript -e 'library(devtools); document(clean=TRUE, reload=TRUE);'

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - git config --global user.email "luckyrandom@gmail.com"
  - git config --global user.name "Chenliang Xu"
  - ./deploy.sh -s master-src -d master -c 'make -k prebuild'

env:
  global:
    secure: "J2eavX8meXVa22qOehk2J7+MISTHXvEDu/CvJeD5qe5E8Hp5GNWBQ8grev0Noj+DT/Aku0or/XDM72W33CU5bfqkQT+BAa7aVCThD1s+tKDg+c5ymIVzAxRJA7whZJcA+gkkNXkO2+qQM+CjKYqcjlniE1DwOLnelm6piVCtpno="
    
branches:
  except:
    ## exclude the deploy branch from build on travis-ci
    - master
    
